spring.application.name=MicroservicioUsuario
server.port=8081

spring.profiles.active=dev

# === CONFIGURACIÓN DE HIBERNATE ===
# Si cambias de equipo o borras la base de datos, usa 'update' temporalmente.
# Para producción, entregas o entorno estricto, usa siempre 'validate'.

spring.jpa.hibernate.ddl-auto=validate


spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true

jwt.secret=secretKeysecretKeysecretKeysecretKey
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true
spring.flyway.validate-on-migrate=false

feign.circuitbreaker.enabled=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha