# Base de datos de TEST (separada del desarrollo)

spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios_shop_now_test?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop