spring.application.name=MicroservicioProducto
server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_productos_shop_now?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=secretKeysecretKeysecretKeysecretKey
spring.flyway.locations=classpath:db/migration

feign.circuitbreaker.enabled=true
spring.flyway.repair-on-migrate=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.htmlspring.flyway.validate-on-migrate=false
